/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sol_busgrupo5.vistas;

import java.sql.Date;
import java.sql.Time;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sol_busgrupo5.accesoADatos.ColectivoData;
import sol_busgrupo5.accesoADatos.PasajeData;
import sol_busgrupo5.accesoADatos.PasajeroData;
import sol_busgrupo5.accesoADatos.RutaData;
import sol_busgrupo5.entidades.Pasaje;

/**
 *
 * @author DANIELALEJANDROMIRAN
 */
public class Ver_Pasaje extends javax.swing.JFrame {
    PasajeData pasajeData = new PasajeData(); PasajeroData pasajeroData = new PasajeroData(); RutaData rutaData = new RutaData(); ColectivoData colectivoData = new ColectivoData();
    /**
     * Creates new form Ver_Pasaje
     */
    public Ver_Pasaje() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("SolBusIcon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ID_Pasaje = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ID_Pasajero = new javax.swing.JTextField();
        ID_Colectivo = new javax.swing.JTextField();
        ID_Ruta = new javax.swing.JTextField();
        Fecha_Viaje = new javax.swing.JTextField();
        Hora_Viaje = new javax.swing.JTextField();
        Asiento = new javax.swing.JTextField();
        Precio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Fecha_Venta = new javax.swing.JTextField();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        JButton_Salir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Estado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ID_Ruta2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Comprobante pasaje");
        setResizable(false);

        jLabel10.setText("                                 ");
        jPanel1.add(jLabel10);

        jLabel1.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel1.setText("ID Pasaje:");
        jPanel2.add(jLabel1);

        ID_Pasaje.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        ID_Pasaje.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ID_Pasaje.setMinimumSize(new java.awt.Dimension(74, 31));
        ID_Pasaje.setPreferredSize(new java.awt.Dimension(74, 31));
        ID_Pasaje.setSelectionColor(new java.awt.Color(204, 204, 255));
        jPanel2.add(ID_Pasaje);

        jLabel11.setText("                                                  ");
        jPanel2.add(jLabel11);

        Buscar.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel2.add(Buscar);

        jLabel2.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DNI pasajero:");

        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Colectivo:");

        jLabel4.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Origen:");

        jLabel5.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Fecha del Viaje:");

        jLabel6.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hora del Viaje:");

        jLabel7.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Asiento:");

        jLabel8.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Precio:");

        ID_Pasajero.setEditable(false);
        ID_Pasajero.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        ID_Pasajero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ID_Pasajero.setMaximumSize(new java.awt.Dimension(64, 31));
        ID_Pasajero.setSelectionColor(new java.awt.Color(0, 102, 51));

        ID_Colectivo.setEditable(false);
        ID_Colectivo.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        ID_Colectivo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ID_Ruta.setEditable(false);
        ID_Ruta.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        ID_Ruta.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Fecha_Viaje.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        Fecha_Viaje.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Hora_Viaje.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        Hora_Viaje.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Asiento.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        Asiento.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Precio.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        Precio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel12.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Fecha de Venta:");

        Fecha_Venta.setEditable(false);
        Fecha_Venta.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        Fecha_Venta.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Modificar.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        Modificar.setText("Modificar");
        Modificar.setEnabled(false);
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Eliminar.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        Eliminar.setText("Remover");
        Eliminar.setEnabled(false);
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        JButton_Salir.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        JButton_Salir.setText("Salir");
        JButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_SalirActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Estado:");

        Estado.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        Estado.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Destino:");

        ID_Ruta2.setEditable(false);
        ID_Ruta2.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        ID_Ruta2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ID_Ruta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ID_Ruta2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JButton_Salir)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Fecha_Venta)
                                .addGap(117, 117, 117))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Fecha_Viaje, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ID_Pasajero, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                    .addComponent(ID_Colectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ID_Ruta)
                                    .addComponent(ID_Ruta2))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Hora_Viaje, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Asiento, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ID_Pasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ID_Colectivo)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_Ruta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_Ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fecha_Viaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Hora_Viaje))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Asiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Fecha_Venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Modificar)
                            .addComponent(Eliminar)
                            .addComponent(JButton_Salir))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_SalirActionPerformed
        dispose();
    }//GEN-LAST:event_JButton_SalirActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        try{
            if(Eliminar.isEnabled()){
                int aux = pasajeData.eliminarPasaje(Integer.parseInt(ID_Pasaje.getText()));
                if(aux==1){
                JOptionPane.showMessageDialog(this, "Pasaje removido.");
                Listar_Pasaje();
                Modificar.setEnabled(false);
                Eliminar.setEnabled(false);
                } else if (aux==0){
                JOptionPane.showMessageDialog(this, "no se pudo remover.");
                Modificar.setEnabled(false);
                Eliminar.setEnabled(false);
                Listar_Pasaje();
                }
            }
        }catch(NumberFormatException NFE){
            JOptionPane.showMessageDialog(this, "Valores erroneos.");
            ID_Pasajero.requestFocus();
            ID_Colectivo.requestFocus();
            ID_Ruta.requestFocus();
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        if(!ID_Pasaje.getText().isEmpty() && pasajeData.BuscarPasaje(Integer.parseInt(ID_Pasaje.getText()))!=null){
            System.out.println(pasajeData.BuscarPasaje(Integer.parseInt(ID_Pasaje.getText())));
            Pasaje pasaje = pasajeData.BuscarPasaje(Integer.parseInt(ID_Pasaje.getText()));
            Listar_Pasaje(pasaje);
            Eliminar.setEnabled(true);
            Modificar.setEnabled(true);
        } else{
            Listar_Pasaje();
        }
        
    }//GEN-LAST:event_BuscarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        try{
            if(Modificar.isEnabled()){
                Pasaje pasaje = new Pasaje(Integer.parseInt(ID_Pasaje.getText()),pasajeroData.buscar("ID", Integer.parseInt(ID_Pasajero.getText())),colectivoData.buscar(Integer.parseInt(ID_Colectivo.getText())),rutaData.buscarPorID(Integer.parseInt(ID_Ruta.getText())),Date.valueOf(LocalDate.parse(Fecha_Viaje.getText())),Time.valueOf(Hora_Viaje.getText()),Integer.parseInt(Asiento.getText()),Double.parseDouble(Precio.getText()),Boolean.parseBoolean(Estado.getText()),Date.valueOf(Fecha_Venta.getText()));
                int aux = pasajeData.modificar(pasaje);
                if(aux==1){
                    JOptionPane.showMessageDialog(this, "Se ha modificado el Pasaje.");
                    Listar_Pasaje();
                    Modificar.setEnabled(false);
                    Eliminar.setEnabled(false);
                } else if (aux==0){
                    JOptionPane.showMessageDialog(this, "No se pudo modificar.");
                    Listar_Pasaje();
                    Modificar.setEnabled(false);
                    Eliminar.setEnabled(false);
                }
            }
        }catch (NumberFormatException NFE){
            JOptionPane.showMessageDialog(this, "Valores erroneos.");
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void ID_Ruta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ID_Ruta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ID_Ruta2ActionPerformed
    public void Listar_Pasaje(Pasaje pasaje){
        Modificar.setEnabled(false);
        Eliminar.setEnabled(false);
        ID_Pasaje.setText(""+pasaje.getIdPasaje());
        ID_Pasajero.setText(""+pasaje.getPasajero().getDni());
        ID_Colectivo.setText(""+pasaje.getColectivo().getMatricula());
        ID_Ruta2.setText(""+pasaje.getRuta().getOrigen());
        ID_Ruta.setText(""+pasaje.getRuta().getDestino());
        Fecha_Viaje.setText(""+pasaje.getFechaViaje());
        Hora_Viaje.setText(""+pasaje.getHoraViaje());
        Asiento.setText(""+pasaje.getAsiento());
        Precio.setText(""+pasaje.getPrecio());
        Estado.setText(""+pasaje.isEstado());
        Fecha_Venta.setText(""+pasaje.getFecha_Venta());
    }
    public void Listar_Pasaje(){
        Modificar.setEnabled(false);
        Eliminar.setEnabled(false);
        ID_Pasaje.setText("");
        ID_Pasajero.setText("");
        ID_Colectivo.setText("");
        ID_Ruta2.setText("");
        ID_Ruta.setText("");
        Fecha_Viaje.setText("");
        Hora_Viaje.setText("");
        Asiento.setText("");
        Precio.setText("");
        Estado.setText("");
        Fecha_Venta.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ver_Pasaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ver_Pasaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ver_Pasaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ver_Pasaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ver_Pasaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Asiento;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField Estado;
    private javax.swing.JTextField Fecha_Venta;
    private javax.swing.JTextField Fecha_Viaje;
    private javax.swing.JTextField Hora_Viaje;
    private javax.swing.JTextField ID_Colectivo;
    private javax.swing.JTextField ID_Pasaje;
    private javax.swing.JTextField ID_Pasajero;
    private javax.swing.JTextField ID_Ruta;
    private javax.swing.JTextField ID_Ruta2;
    private javax.swing.JButton JButton_Salir;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField Precio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
